IUT-22 Create FilterChip
implentio/ui-toolkit pull request #13
Opened 2024-02-05 20:00 UTC by GitJustinLau

## Description
This component renders chips specifically for filters.

Props: "variants", "filterName"

Variants:
- "addFilter": a chip where (ex. on clicking) you can add additional filters 
- "filterValue" a chip to display currently filters being applied

filterName:
- the name of the filter. Only applicable when variant = filterValue

## Link to JIRA ticket
[Include the link here.](https://implentio.atlassian.net/jira/software/projects/IUT/boards/10?selectedIssue=IUT-22)

## Applicable Screenshots
**variant="filterValue" filterValue="test"**
default:
![image](https://github.com/implentio/ui-toolkit/assets/93560211/ed779858-4347-4dbc-8fd5-82d83522504d)
hover on button:
![image](https://github.com/implentio/ui-toolkit/assets/93560211/ea7ee5a4-1b8d-4ad3-8279-f989712ae9b1)
hover on X:
![image](https://github.com/implentio/ui-toolkit/assets/93560211/13a6e506-a650-4c16-a1b1-317990980993)

**variant="addFilter" filterValue="test"**
default:
![image](https://github.com/implentio/ui-toolkit/assets/93560211/f10b6cf0-d480-4720-a757-dd8cd1fe9011)
hover on button:
![image](https://github.com/implentio/ui-toolkit/assets/93560211/fe2ca7c2-ae62-4f1a-be63-f3b6ec35c550)

## Testing Instructions
Outline the steps required to test your changes effectively (Replace the following to what makes sense for your PR):
- Fetch and checkout my branch `git fetch && git checkout <feat/IUT-22/filterChip>`
- npm run storybook
- Check to see that the behavior follows figma
  - on hover styles change

## Checklist:
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have tested my code thoroughly.
- [ ] I made documentation changes (optional).

## Provide feedback:
- line 6: I have used 'text-body/small/w-medium' which is currently having a bug. To get around it I have also input its style directly as a temporary solution: 'font-medium text-leading-[1.3rem] text-tracking-[-0.01rem]' Is this ok?
- line 22: filterName is a required prop. However, its only useful and required when variant = filterValue.

2024-02-05 20:09 UTC, launchupio commented
Good job @GitJustinLau ! Heads up, make sure you give the story a specific name instead of `FirstStory`

2024-02-05 20:17 UTC, joseph-hc-jun commented on src/index.css
> +  src: url("/fonts/Inter-VariableFont_slntwght.ttf");
Was it intentional to change the name of the file? I think the name originally was with `,`, does it work without it?

2024-02-05 20:36 UTC, GitJustinLau commented on src/index.css
> +  src: url("/fonts/Inter-VariableFont_slntwght.ttf");
I did not intentionally change that. I have replaced the , because it does not work without it.

2024-02-05 20:48 UTC, joseph-hc-jun commented on src/components/FilterChip/FilterChip.tsx
> +  const [isHovered, setIsHovered] = React.useState(false)
I see why you used state here, but can you look for a way to do it without? 
I think things are simpler without state on these small component level.

I'm not sure how Tailwind handles it, but in another design framework, we can select children elements with something like,
```
"&:hover svg": {
 styles go here
}
```

2024-02-05 20:53 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.tsx
> +  const [isHovered, setIsHovered] = React.useState(false)
sounds good ill look into it!

2024-02-05 21:09 UTC, joseph-hc-jun commented on src/components/FilterChip/FilterChip.tsx
> +  filterName: string;
Looking at the design again, we might want to have more props I think.
```
filter?: string; // In example, value of this is "Filter:"
value: string; // If addView is true, this should be the string in the button I think?
addView: boolean;
onRemove?: function // if we pass in value here, X button appears and runs the function upon click
onClick: function // to run on button click
```
Please let me know what you think, I might've overlooked something here :)

2024-02-05 21:12 UTC, joseph-hc-jun requested changes
From your screenshot, 
- the gap between the text and X button looks a bit different
- the dotted line has longer strokes on design doc
Can you take another look and update it please? Thanks!

2024-02-05 21:31 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.tsx
> +  const [isHovered, setIsHovered] = React.useState(false)
I have applying groupings: https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

2024-02-05 22:35 UTC, GitJustinLau commented
> From your screenshot,
> 
> * the gap between the text and X button looks a bit different
> * the dotted line has longer strokes on design doc
>   Can you take another look and update it please? Thanks!

I have fixed the sizing of the chip: 
![image](https://github.com/implentio/ui-toolkit/assets/93560211/6f97bac1-2f9b-459a-bccf-a71f8f73dcc8)

This includes changing the padding within the OnRemove component. 
I don't think tailwind supports changing the border-dash length or spacing

2024-02-06 16:35 UTC, joseph-hc-jun commented on src/components/FilterChip/FilterChip.tsx
> +  "inline-flex items-center justify-center whitespace-nowrap rounded-md gap-1 border py-1 text-body/small/w-medium text-[12px] font-medium text-leading-[1.3rem] text-tracking-[-0.01rem] group",
Is the way you defined text styles here because of the limitations of the library where `text-` classes appear multiple times that the previous ones get ignored even though they are for different purposes?
If then, let's have this in and change it back in the future if we discover a better solution. Can you also update `StatusChip` component to use this if you haven't done it already?

2024-02-06 16:35 UTC, joseph-hc-jun commented on src/components/FilterChip/FilterChip.stories.tsx
> +// import { Onremove } from "../OnRemove/OnRemove";
Let's remove the comment if not used here 😄

2024-02-06 16:36 UTC, joseph-hc-jun approved these changes
Looks great, please feel free to merge in after addressing the comments below!

2024-02-06 17:52 UTC, merged

2024-02-07 16:14 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.tsx
> +  "inline-flex items-center justify-center whitespace-nowrap rounded-md gap-1 border py-1 text-body/small/w-medium text-[12px] font-medium text-leading-[1.3rem] text-tracking-[-0.01rem] group",
yes that is why i have that redundancy! we will defintely have to remove it after we solve the issue. Will add to status chip as well