add NavItem component
implentio/ui-toolkit pull request #16
Opened 2024-02-07 03:49 UTC by GitJustinLau

## Description
This is the navigation item component. Will be used to assemble the navbar

2 Variants:
type = "single" | "group"

## Link to JIRA ticket
[Include the link here.](https://implentio.atlassian.net/jira/software/projects/IUT/boards/10?selectedIssue=IUT-27)

## Testing Instructions
Outline the steps required to test your changes effectively (Replace the following to what makes sense for your PR):
- Fetch and checkout my branch `git fetch && git checkout <feat/IUT-27/NavItem>`
- npm run storybook
- Check to see that the elements are aligned, text is properly showing, and there is a hover effect changing text color to brand-emphasis

## Checklist:
Check what is applicable by putting an 'x' in between the []:
- [x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] I have tested my code thoroughly.
- [ ] I made documentation changes (optional).

2024-02-07 16:14 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +  title: string;
Maybe we need another boolean prop named `active` for a different style when the item is selected.

2024-02-07 16:16 UTC, joseph-hc-jun commented
Thanks for the quick PR!. I'd like to discuss with you on the approach here for the possibility to use `Accordion` component in shadcn/ui.

2024-02-07 16:41 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +  title: string;
ok!

2024-02-07 20:38 UTC, neli-rashkova commented on src/components/NavItem/NavItem.tsx
> +    </div>
`className` is a prop that seems to not be used in your component. If its not necessary, you can remove it.

2024-02-09 16:55 UTC, joseph-hc-jun commented on src/components/Tooltip/Tooltip.tsx
> +import * as React from "react"
I'm wondering why these files are shown as your changes, do you remember whether you used `git merge main` or `rebase`?

2024-02-09 17:59 UTC, GitJustinLau commented on src/components/Tooltip/Tooltip.tsx
> +import * as React from "react"
oh there was a rebase issue. now fixed

2024-02-10 15:29 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +    </div>
added. i think it helps when users want to add additional classnames

2024-02-10 17:02 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
Here as well, let's let the parent component dictate the width by giving it 100% width here.

2024-02-10 17:04 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
Just a note for now, but once the `text-` style conflicts get resolved, let's change `font-medium` to the named variable instead.

2024-02-10 17:05 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
Question: is `data-active={active}` necessary for giving the right style on active state? Or is it for something else?

2024-02-10 17:07 UTC, joseph-hc-jun requested changes
We're almost there I feel, left a bit more comments including a question for you!

2024-02-10 19:13 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
sounds good. once it is resolved i will review my components

2024-02-10 19:13 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
it needs to be passed into the div so that the tailwind class can pick up the state of data-active

2024-02-10 19:30 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +      className={"flex items-center px-2 py-3 w-[208px]  font-medium group "+`${type==="single" && "data-[active=true]:bg-bg-color-brand-disabled"}` + className} data-active={active}
yep. you're right. ill be more careful to apply changes to all my PRs for any changes that can apply to more than one

2024-02-10 20:12 UTC, joseph-hc-jun approved these changes

2024-02-10 20:15 UTC, merged