added strict type guard for onRemove prop
implentio/ui-toolkit pull request #17
Opened 2024-02-07 17:10 UTC by GitJustinLau

# Pull Request Template

## Description
onRemove is a prop which is only required and useful when addView = false. However, it can currently be input when addView=true. This PR changes the typing so that onRemove cannot be passed when addView=true

## Link to JIRA ticket
[Include the link here.](https://implentio.atlassian.net/jira/software/projects/IUT/boards/10?selectedIssue=IUT-35)

## Testing Instructions
Outline the steps required to test your changes effectively (Replace the following to what makes sense for your PR):
- Fetch and checkout my branch `git fetch && git checkout <fix/IUT-35/Update-FilterChip-w-type-guard>`
- Go to src/components/FilterChip/FilterChip.tsx
- on the bottom of the page, copy and paste: `<FilterChip addView={false} value="value" filter="filter: " onRemove={()=> console.log("test")} />`
- check if typescript throws type errors when you add and remove props and when you toggle addView to true/false

## Checklist:
Check what is applicable by putting an 'x' in between the []:
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested my code thoroughly.
- [ ] I made documentation changes (optional).

2024-02-07 17:36 UTC, launchupio requested changes
Please see comments! Make sure you start using actions please!

2024-02-07 17:36 UTC, launchupio commented on src/components/FilterChip/FilterChip.stories.tsx
> +    onRemove: () => console.log("test")
Use actions for action related functions being called so we can leverage storybook's action tab.

At top of file:
`import { action } from '@storybook/addon-actions';`

```suggestion
    onRemove: () => action('onRemove')
```

more on it here: https://storybook.js.org/docs/essentials/actions

2024-02-07 17:36 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
>        {!addView && (
I know it's part of the former PR of yours that already got okayed, but it looks like we missed this. We should simplify this to ternary to show it's outcome more clearly:
```
{ addView ? value : <p></p> }
~``

2024-02-07 18:04 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.stories.tsx
> +    onRemove: () => console.log("test")
change made

2024-02-07 18:07 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.tsx
>        {!addView && (
ok change added

2024-02-07 19:33 UTC, launchupio requested changes

2024-02-07 19:33 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
> -  onRemove,
taking this out causes this warning: 
![Screenshot 2024-02-08 at 4 31 51 AM](https://github.com/implentio/ui-toolkit/assets/58754597/8709c543-99f7-4298-8e41-521e31fdd481)

If you keep this in, you'll need to edit FilterChipProps, as I've commented above.

2024-02-07 19:33 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
> +  (addView | filterValue);
If you leave in onRemove in line 32, you probably need to switch this around to something like:

```suggestion
export type FilterChipProps = React.HTMLAttributes<HTMLDivElement> &
  VariantProps<typeof FilterChipVariants> &
  (addView | filterValue)  & {
    onRemove?: () => void; 
  };
```

2024-02-07 20:43 UTC, launchupio requested changes
Made some errors in my requested changes, and now i'm suggesting some other solutions as examples. You don't need to follow the ideas i wrong out though.

2024-02-07 20:43 UTC, launchupio commented on src/components/FilterChip/FilterChip.stories.tsx
> +    onRemove: () => action('onRemove')
i think i originally asked for `onRemove: () => action('onRemove')` but it doesn't work. check docs. i think it should instead be `onRemove: action('onRemove')` instead perhaps

2024-02-07 20:43 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
> -  onRemove,
Never mind the idea of keeping it in. You can take it out like you had, but then have to deal with your current `...props` situation. I'll make comments elsewhere for an idea.

2024-02-07 20:43 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
>      <div className={cn(FilterChipVariants({ className, addView }))} {...props}>
Dont' take verbatim, but something like this?

```suggestion
   let onRemoveProp;
  let restProps = props;
  
  if('onRemove' in props) {
    const { onRemove, ...otherProps } = props;
    onRemoveProp = onRemove;
    restProps = otherProps;
  }

  return (
    <div className={cn(FilterChipVariants({ className, addView }), className)} {...restProps}>
```

2024-02-07 20:43 UTC, launchupio commented on src/components/FilterChip/FilterChip.tsx
> +          )}
```suggestion
{addView ? (
        value
      ) : (
        <>
          <p>
            {('filter' in props ? props.filter : '')} <span className="font-regular">{value}</span>
          </p>
          {'onRemove' in props && (
            <OnRemove
              size="md"
              className="group-hover:text-icons-default"
              onClick={onRemoveProp}
            />
          )}
        </>
      )}
```

2024-02-07 20:50 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.stories.tsx
> +    onRemove: () => action('onRemove')
Ok will confirm

2024-02-07 23:12 UTC, GitJustinLau commented on src/components/FilterChip/FilterChip.stories.tsx
> +    onRemove: () => action('onRemove')
seems like action is for triggering an action when an event happens. The onRemove prop is for passing down a callback function. I think they have separate purposes, lmk.

![image](https://github.com/implentio/ui-toolkit/assets/93560211/27c5d438-3029-400f-9c99-379e56ae5987)

2024-02-08 18:34 UTC, launchupio commented on src/index.css
> -    --bg-brand-disabled: 249 58% 95%;     /* Icon Button */
@GitJustinLau just want to confirm if deleting this is intentional?

2024-02-08 18:37 UTC, GitJustinLau commented on src/index.css
> -    --bg-brand-disabled: 249 58% 95%;     /* Icon Button */
this is the same variable i am using that has replaced the one removed: 
![image](https://github.com/implentio/ui-toolkit/assets/93560211/70d73038-bf63-4d8c-a4b2-64dc7205c5f4)

2024-02-08 19:15 UTC, launchupio approved these changes
👨 🚀 🌔 

Gj!

2024-02-08 19:38 UTC, merged