Feat: Create CollapsedMenu Component
implentio/ui-toolkit pull request #20
Opened 2024-02-09 17:48 UTC by neli-rashkova

## Description
Created `CollapsedMenu` component that consists of a caption and a sublist. Clicking on the trigger content will display the collapsed menu.
Props:

- triggerContent: the component passed in that will be the trigger content.
- caption: string
- subList: an array of objects, each object has two properties, text and onClick

## Link to JIRA ticket
[Link to JIRA ticket](https://implentio.atlassian.net/browse/IUT-29?atlOrigin=eyJpIjoiMjkyNTRlZWI0M2NkNGEzNmIxMTU1ZDU3ZGZhZjdkYWYiLCJwIjoiaiJ9)

## Applicable Screenshots
**Note: Icon component is used as an example trigger content to click on and show how collpased menu component renders**
<img width="244" alt="Screenshot 2024-02-09 at 10 46 01 AM" src="https://github.com/implentio/ui-toolkit/assets/104450960/4758b03c-c104-4377-8d88-db34be0418cc">
<img width="240" alt="Screenshot 2024-02-09 at 10 46 20 AM" src="https://github.com/implentio/ui-toolkit/assets/104450960/93bfca0c-8b3a-4e4b-9e69-d8e641d2fe74">
<img width="317" alt="Screenshot 2024-02-09 at 10 46 29 AM" src="https://github.com/implentio/ui-toolkit/assets/104450960/a91e24c8-03b4-4879-a461-fe40eb9f988c">
<img width="323" alt="Screenshot 2024-02-09 at 10 46 36 AM" src="https://github.com/implentio/ui-toolkit/assets/104450960/5259dc2d-1ea4-45a0-a6c3-ddb6ff4695fc">

## Testing Instructions
- Fetch and checkout my branch `git fetch && git checkout feat/IUT-29/CollapsedMenu`
- `npm run storybook`
- Check to see that when clicking on trigger content, the collapsed menu is displayed. Hover over sublist.

## Checklist:
Check what is applicable by putting an 'x' in between the []:
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have tested my code thoroughly.
- [ ] I made documentation changes (optional).

2024-02-09 17:56 UTC, launchupio requested changes
@neli-rashkova sorry for adding in additional design work here, but the hover state has actually now been specified by design team. Can you take al ook at this and change the designs accordingly and ping me again after when PR is ready?

Appreciate it!

https://www.figma.com/file/UYBp8YXmCgUqhiOsrkHd6V/Implentio-Library?type=design&node-id=182-13759&mode=design&t=x0pNTA0argGLEzaQ-0

2024-02-09 18:07 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Test")
all of these should use storybook actions instead: e.g. `onClick: action('reportsClick')`

2024-02-09 18:07 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Testing")
all of these should use storybook actions instead

2024-02-09 18:07 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Test")
all of these should use storybook actions instead

2024-02-09 18:07 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Testing")
all of these should use storybook actions instead (name them better too)

2024-02-09 18:08 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +
import storybook actions

2024-02-09 18:08 UTC, launchupio commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +        <IconButton icon={'MagnifyingGlassIcon'} size='medium' onClick={() => console.log('Hello')} />
use storybook action for onClicks

2024-02-09 19:30 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Test")
fixed

2024-02-09 19:30 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Testing")
fixed

2024-02-09 19:30 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Test")
fixed

2024-02-09 19:30 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +                onClick: () => console.log("Testing")
fixed

2024-02-09 19:30 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +
ok!

2024-02-10 18:49 UTC, neli-rashkova commented on src/components/CollapsedMenu/CollapsedMenu.stories.tsx
> +        <IconButton icon={'MagnifyingGlassIcon'} size='medium' onClick={() => console.log('Hello')} />
ok!

2024-02-11 02:41 UTC, joseph-hc-jun approved these changes
Looks good! Thank you :)

2024-02-11 03:07 UTC, launchupio approved these changes
🚀

2024-02-11 04:04 UTC, merged