Feat IUT-39/menu group
implentio/ui-toolkit pull request #23
Opened 2024-02-11 02:10 UTC by GitJustinLau

## Description
This is the component used in the navigation bar which groups menu items together. It can include single navigation items and grouped navigation items. Grouped navigation items have a collapsed subitem group which expands on click. Clicking subNav items will navigate a page. For single nav items, clicking on it will navigate to a page

## Link to JIRA ticket
https://implentio.atlassian.net/jira/software/projects/IUT/boards/10?selectedIssue=IUT-39

## Applicable Screenshots

## Testing Instructions
- Fetch and checkout my branch `git fetch && git checkout <feat/IUT-39/MenuGroup>`
- npm run storybook into the CLI
- Check the following behaviors for the MenuGroup:

1. Clicking on grouped navitems will expand a subnav group and does not trigger an action
3. clicking a subnav item will trigger an action
4. clicking a single (does not have a chevron) navItem will trigger an action
5. hovering will change text and chevron to purple (hover color) from blackish (default color)
6. in the GroupActive story, the action group has purple text and its subnav item has purple text and a purple bg
7. in the singleActive story, the navitem has purple text and bg
8. when toggling the MenuGroup type ("single" | "multiple"), single will only allow one grouped item to be expanded
9. if type is multiple, you can have multiple nav groups open
10. 

## Checklist:
Check what is applicable by putting an 'x' in between the []:
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have tested my code thoroughly.
- [ ] I made documentation changes (optional).

2024-02-11 03:17 UTC, joseph-hc-jun commented
Some feedback I have from looking at deploy preview:
1. on hover & active state, let's add in the border radius.
2. `cursor: pointer` on sub nav item is missing.
3. the right/down arrow should be aligned to the right.
note: if it looks weird spanning across the whole screen on Storybook, we could put it into a div with a set width!

2024-02-11 03:26 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +export type singleProps = {
If the types are internal purposes, we might not want to export them :)

2024-02-11 03:41 UTC, joseph-hc-jun commented on src/components/MenuGroup/MenuGroup.tsx
> +  const accordionItems = itemArr.map((item) => {
One thing I'd like to point out here, this might not be a big deal in this case (and it's very commonly done too) but generally I don't think it's a good idea to define this kind of complex logic inside a component.

This way, whenever component re-renders (this happens quite a lot) this variable definition will re-run too (it's long and includes a loop, so quite expensive) which isn't necessary.

What we can do instead is,
1. defining it as a function that takes in an argument (in this case `itemArr`), and returns jsx. This way we can take the definition outside of the component and have it defined somewhere like line 20. Then you simply call it with the argument in the same place you used it.
2. You can memoize the function definition with the use of `useMemo` hook (`useCallback` if you want to make it into function). You can read more about it (here)[https://react.dev/reference/react/useMemo].

2024-02-11 03:46 UTC, joseph-hc-jun requested changes
Looks great in general, requested some changes so please take a look. Thank you!

2024-02-11 04:32 UTC, GitJustinLau commented on src/components/NavItem/NavItem.tsx
> +export type singleProps = {
oh i need to import them into the MenuGroup component. I won't include it into the src index export

2024-02-11 04:52 UTC, GitJustinLau commented
> Some feedback I have from looking at deploy preview:
> 
> 1. on hover & active state, let's add in the border radius.
> 2. `cursor: pointer` on sub nav item is missing.
> 3. the right/down arrow should be aligned to the right.
>    note: if it looks weird spanning across the whole screen on Storybook, we could put it into a div with a set width!

1. done. added to default and it show stay for both hover and active. default doesnt have a bg so it wont be visible
2. added. also added to navItem (neither mentioned cursor pointer so ill put onto both)
3. it is currently set to a fixed width but not right aligned. Added right align for chevron. Removed fixed width for production. I guess it will look a bit weird but with context, it makes sense

lmk if you want any of these points adjusted

2024-02-11 22:31 UTC, joseph-hc-jun commented on src/components/NavItem/NavItem.tsx
> +export type singleProps = {
Oh that makes sense, thanks for the answer!

2024-02-11 22:42 UTC, joseph-hc-jun commented on src/components/MenuGroup/MenuGroup.tsx
> +  const accordionItems = React.useMemo(
Thanks for making the change here! By defining it outside the component it would have the same effect as using `useMemo` already, so doing it here isn't strictly necessary here but it's just my small nit 😄

2024-02-11 22:44 UTC, joseph-hc-jun approved these changes
Looks great! Awesome job completing one of the more complex components! 👍

2024-02-12 04:32 UTC, GitJustinLau commented on src/components/MenuGroup/MenuGroup.tsx
> +  const accordionItems = React.useMemo(
oh i see first time using it

2024-02-12 04:40 UTC, merged